language: node_js
node_js:
  - "lts/*"
  - "8.14.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile
